#!/usr/bin/env python3
"""One-command setup for APEX remote notify + control.

Generates the scary bits for you (a strong signing secret + two unguessable topic names)
and writes them to a `.env` file. You never have to invent these yourself.

Usage:
    python3 scripts/setup_comms.py            # create .env (won't clobber an existing one)
    python3 scripts/setup_comms.py --force    # overwrite an existing .env

Decisions baked in (chosen for a novice — zero servers to run):
  * Backend  : ntfy.sh public server (no hosting, no account needed).
  * Security : every control command is HMAC-signed (defense even on a public topic).
  * Topics   : random + unguessable, and notify/control are kept separate.
After running, follow the printed steps. To go live, set NTFY_ENABLED=true.
"""
from __future__ import annotations

import argparse
import os
import secrets
import sys

ENV_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")


def build_env() -> str:
    suffix = secrets.token_hex(8)  # 16 hex chars -> unguessable
    notify_topic = f"apex-{suffix}-notify"
    control_topic = f"apex-{suffix}-control"
    hmac_secret = secrets.token_urlsafe(32)
    return (
        "# APEX remote notify + control (Phase 5D). Generated by scripts/setup_comms.py.\n"
        "# KEEP THIS FILE PRIVATE — it is gitignored. Anyone with these values can\n"
        "# read your alerts and send control commands.\n"
        "\n"
        "# Flip to true once you've tested reachability (see docs §12).\n"
        "NTFY_ENABLED=false\n"
        "\n"
        "NTFY_BASE_URL=https://ntfy.sh\n"
        f"NTFY_NOTIFY_TOPIC={notify_topic}\n"
        f"NTFY_CONTROL_TOPIC={control_topic}\n"
        f"NTFY_HMAC_SECRET={hmac_secret}\n"
        "\n"
        "# Optional hardening (later): if you self-host ntfy or use ntfy.sh reserved\n"
        "# topics, paste per-topic tokens here.\n"
        "# NTFY_READ_TOKEN=\n"
        "# NTFY_WRITE_TOKEN=\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = parser.parse_args()

    if os.path.exists(ENV_PATH) and not args.force:
        print(f"Refusing to overwrite existing {ENV_PATH} (use --force).")
        return 1

    content = build_env()
    with open(ENV_PATH, "w", encoding="utf-8") as fh:
        fh.write(content)
    os.chmod(ENV_PATH, 0o600)

    notify = next(line.split("=", 1)[1] for line in content.splitlines() if line.startswith("NTFY_NOTIFY_TOPIC="))
    control = next(line.split("=", 1)[1] for line in content.splitlines() if line.startswith("NTFY_CONTROL_TOPIC="))

    print(f"Wrote {ENV_PATH} (permissions 600).\n")
    print("Next steps:")
    print("  1. Install the 'ntfy' app on your phone (Play Store / App Store).")
    print(f"  2. In the app, Subscribe to BOTH topics: {notify}  and  {control}")
    print(f"  3. Test reachability on your real connection (Wi-Fi AND mobile data):")
    print(f"       curl -d \"test\" https://ntfy.sh/{notify}")
    print("     If the push lands on your phone, ntfy works on your network.")
    print("  4. Set NTFY_ENABLED=true in .env, then load it before starting the bot.")
    print("\nIf step 3 never arrives, ntfy.sh may be blocked — tell Claude and we'll")
    print("switch to a self-hosted server (one env var changes, no code changes).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
